### ISSUE TITLE
fix(tests): restore the createClient import in db.test.ts so deploy-dev goes green

### ISSUE THREAD

**Issue by sv-tmueller** [sv-tmueller/trading-bot#516]
Part of batch #515

## What to build

`main` fails `deno task test` type-checking, which fails deploy-dev's test job and skips the deploy step, so none of the six fixes merged on 2026-08-02 (PRs #502, #503, #506, #507, #510, plus research #505) nor migration `0015_hourly_check_http_timeout.sql` have reached the dev/paper project. Restore a green `main` so deploy-dev ships them.

Root cause (verified on `origin/main`): a semantic merge conflict between PR #510 (#487), which added the `wireCapturingClient` helper calling `createClient` at `supabase/functions/_shared/db.test.ts:1209`, and PR #503 (#485), which rewrote that file's import block to route through `db_test_guard.ts`. Each PR was green alone; combined, `createClient` has no import. CI error: `TS2304: Cannot find name 'createClient'` at `db.test.ts:1209`.

**Time-critical: must merge (and deploy-dev complete) before Monday 2026-08-04 13:07 UTC, the first hourly-check cron slot.** Until then the live bot runs the 2026-07-31 code on pg_net's 5000 ms default timeout.

## Acceptance criteria

- [ ] `deno task test` passes on `main`'s combined state (the fix branch is based on current `main`).
- [ ] The fix restores the import (or equivalent minimal change); no test assertions change, no production code changes.
- [ ] After merge, the deploy-dev workflow run completes: test job green, deploy job runs including `supabase db push` (verifiable post-merge; the PR itself proves the test job).
- [ ] Satisfies all CLAUDE.md Architectural invariants; any violation is a must-fix review finding.

## Non-goals

- No behavioral change to any production or test logic beyond restoring the missing import.
- No investigation of why CI on the two PR branches could not catch the cross-PR conflict (that is process follow-up, not this fix).

**Comment by sv-tmueller** [comment]
SUB_PLAN (architect, batch #515)

# Sub-plan: #516 — restore a green `main` so deploy-dev ships

## Finding that changes the approach (verified empirically)

The issue title says "restore the `createClient` import", but the import-only fix **does not go green**. PR #503 also added `supabase/functions/_shared/db_test_guard.test.ts` with a coupling-scan test — `"db.test.ts builds its client through createLocalDbClient, never createClient directly"` — asserting db.test.ts source contains no `createClient(` call at all. CI never surfaced this because type-checking aborts before any test runs.

Both candidates verified on an isolated copy of `origin/main`:
- **Import-only fix:** type-check passes, then the scan test fails (`15 passed | 1 failed`). Ruled out by acceptance criterion 1.
- **Guard-helper fix (below):** `deno task test` → **776 passed, 0 failed, 20 ignored**; lint and fmt:check clean.

The issue's "(or equivalent minimal change)" covers this — no NEEDS_DECISION; the import-only reading is mechanically ruled out. Confirmed via the CI log and a full `deno check`: the TS2304 at `db.test.ts:1209` is the **only** type error on origin/main.

**Rejected variant (do not take this shortcut):** alias-importing `createClient as ...` in db.test.ts evades the source scan while keeping direct construction — the scan test's own comment classifies exactly this as deliberate evasion; the reviewer must block it.

## Approach

Route the #487 wire-stub client construction through `db_test_guard.ts` — the file that already owns all Supabase client construction for tests. Satisfies the type-checker, keeps the #503 coupling scan green without weakening it, and cannot reintroduce the #485 hazard: the helper hard-codes `http://stub.invalid` (RFC 2606 reserved TLD) and the transport is the caller's fetch stub, so no request leaves the process.

## Files touched (test infrastructure only; zero production code, zero assertion changes)

1. `supabase/functions/_shared/db_test_guard.ts` — append one exported helper (`createClient` and `SupabaseClient` already imported there):

```ts
/**
 * A real supabase-js client whose transport is the caller's fetch stub and
 * whose URL is a reserved .invalid host, so no request can leave the process
 * even if the stub is misused. For wire-level assertions on the emitted HTTP
 * request (#487), not for the RUN_DB_TESTS gated suite.
 */
export function createWireStubClient(fetchStub: typeof fetch): SupabaseClient {
  return createClient("http://stub.invalid", "stub-service-role-key", {
    auth: { persistSession: false },
    global: { fetch: fetchStub },
  });
}
```

2. `supabase/functions/_shared/db.test.ts` — two hunks: add `createWireStubClient` to the line-2 import from `./db_test_guard.ts`; in `wireCapturingClient` (~line 1209) replace the four-line `const sb = createClient(...)` block with `const sb = createWireStubClient(fetchStub as typeof fetch);`

Net diff: +19/-6 across two test files.

## Order of work

1. Branch `fix/516-db-test-wire-stub-client` from `origin/main` (commit `4862852`), in a worktree.
2. Reproduce first: `deno task test` must fail with TS2304 at `db.test.ts:1209`.
3. Apply hunk 1, then hunk 2.
4. Verify: `deno task test` (expect 776 passed, 0 failed, 20 ignored); `deno test --allow-env --allow-net --allow-read=supabase/functions,scripts supabase/functions/_shared/db_test_guard.test.ts` (expect 16 passed); `deno task lint`; `deno task fmt:check`.
5. PR against `main`.

## PR

- Title: `fix(tests): route the db.test.ts wire-stub client through db_test_guard (#516)` (deliberately not "restore the import" — the import-only fix is demonstrably red; say so in one sentence in the body).
- Body: `Closes #516`, test-infrastructure-only note, verification output.

## Post-merge verification (time-critical)

Merge before **Monday 2026-08-04 13:07 UTC**. After merge: deploy-dev test job green, deploy job runs `supabase functions deploy` + `supabase db push` (applies 0015). A green run takes ~4 minutes.

## Invariants check

No broker surface touched; the #485 guard is not weakened (db.test.ts still constructs zero clients directly; the helper cannot reach any host); coupling-scan test stays byte-identical; no decision-rule/LLM/paper-guard/panic surface involved.

## Size label check

size:S accurate: two test files, ~25 lines, single verified approach.

**Comment by sv-tmueller** [comment]
Package complete: PR #517 is ready for review (tester PASS round 1, reviewer APPROVE round 1, no findings either stage). UNTESTED CLAIM for the human merge: acceptance criterion 3 (deploy-dev completes incl. supabase db push) is verifiable only post-merge — after merging, confirm the deploy-dev run goes green and migration 0015 lands (the cron.job command gains timeout_milliseconds := 120000). Time-critical: merge before Monday 2026-08-04 13:07 UTC.
